title: Hrushikesh Jetti | @OnlyBugs05
description: Bug Bounty Hunter, Cybersecurity Enthusiast, and Solidity Developer.
url: "https://hrushikeshjetti.dev"
author:
  name: Jetti Hrushikesh
  github: onlybugs05
  twitter: onlybugs05

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom Theme Settings
accent_color: "#00F72B"
google_fonts: "Inter:wght@400;700|Fira+Code:wght@400;700"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

